### ISSUE TITLE
Profile View pushed in the navigation infinitely

### ISSUE THREAD

**Issue by scoder1747** [damus-io/damus#104]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/120697811/209230174-44b4ceb5-3357-49e8-b215-f900400fc10e.gif)

**Comment by jb55** [comment]
I have never experienced this. bizarre

**Comment by jb55** [comment]
oh I see what you mean. yeah we can fix this

**Comment by alltheseas** [comment]
I think this is fixed @scoder1747. Can you close if fixed?

**Comment by scoder1747** [comment]
> I think this is fixed @scoder1747. Can you close if fixed?

This behavior still persists. The user shouldn't be navigated to the profile by tapping on the image/link if he is viewing the same profile.

cc @jb55

**Comment by alltheseas** [comment]
@scoder1747 I don't understand how to recreate this issue. 

Could you please start from e.g. closing Damus app, opening Damus app, and recording your screen from there 🙏

**Comment by alltheseas** [comment]
I see what you mean now @scoder1747

**Comment by alltheseas** [comment]
Related: infinite hashtag rabbit hole

**Comment by jb55** [comment]
Not fixed yet

**Comment by jb55** [comment]
nm this is fixed, just not hashtags yet
