### ISSUE TITLE
Bug: smol phone (iPhone SE) side menu scroll is broken

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2352]
**What happens**
iPhone SE user, 1.9
Larger font size
When I open the side menu bar, I cannot scroll up and down

** What I expect to happen **
I expect to be able to scroll up and down the side menu bar

https://damus.io/nevent1qqs2utgraa8zyfq7tw8kr62m8rmp6gtyt60zwhgq03qlyt08lzfs5vgpp4mhxue69uhkummn9ekx7mqpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqgswaehxw309ahx7um5wgh8w6twv5q3gamnwvaz7tmjv4kxz7fwv3sk6atn9e5k7j7vqhz

**Comment by alltheseas** [comment]
I could not recreate on a 13 mini. I asked the bug reporter to share their iOS version

**Comment by askeew** [comment]
I've investigated this and I suggest we close this issue since:
- In the issue-description user cannot scroll, but the users screen dump shows that the users has scrolled to the bottom
- `ConfigView` uses Apples Form which is a List which is Scrollable. 
- Verified that `ConfigView` works as expected on iPhone SE iOS 18.2 (simulator)

**Comment by alltheseas** [comment]
iOS version is 17.5.1

Some SE cannot run iOS 18 if I recall

**Comment by askeew** [comment]
My investigation suggest that this has been fixed in Damus v 1.15 (1) 94571ede. 
Since I (we?) cannot recreate it, maybe we should close it and if someone still has this problem we can open a new issue?

**Comment by alltheseas** [comment]
Thanks @askeew - can you confirm you
1) ran iOS 17, and
2) tested on device?

I followed up with the bug reporter to check if they are still experiencing this bug.

**Comment by alltheseas** [comment]
@danieldaquino advised 3rd gen SE is big enough screen for side menu to work. Closing for now unless we hear otherwise
